### ISSUE TITLE
uvisor-lib.h include guard should check if uvisor:present is true

### ISSUE THREAD

**Issue by akselsm** [ARMmbed/uvisor#107]
The YOTTA_CFG_UVISOR_PRESENT check in uvisor-lib.h should also check for truthiness, in order to work with targets defining `"uvisor": { "present": false }`.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1200

**Comment by AlessandroA** [comment]
Fixed with https://github.com/ARMmbed/uvisor/issues/109
