### ISSUE TITLE
Add debug-time/run-time fixes for broken porting / Interrupts

### ISSUE THREAD

**Issue by meriac** [ARMmbed/uvisor#112]
- verify if interrupts are enabled before they are set
  - each attempt to change the enable-state of an interrupt while it's not assigned to the calling box must fail with a security exception. This allows detecting race conditions in application code.

Note: changes above prevent bugs like https://github.com/ARMmbed/uvisor/issues/87

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1362

**Comment by meriac** [comment]
Moved first point to https://github.com/ARMmbed/uvisor/issues/159 - dropped third point as a duplicate of the first point applied to both debug & release build.
