### ISSUE TITLE
Modify g_vmpu_box_count so that box 0 is included in the count

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#120]
Now that box 0 has its own ACLs, it makes sense to include it in the count kept in `g_vmpu_box_count`.
The code in the `vmpu` module should be changed accordingly to avoid off-by-one errors.

**Comment by avri-schneider** [comment]
See the following comment: https://github.com/ARMmbed/uvisor/commit/f98b83fa130cc21d1e687f481eefa0e3bfa73779#commitcomment-15234232

**Comment by AlessandroA** [comment]
Fixed in https://github.com/ARMmbed/uvisor/pull/128
