### ISSUE TITLE
Add mutli-box support to vmpu_load_box

### ISSUE THREAD

**Issue by Joouis** [ARMmbed/uvisor#130]
Hi,
- We want to create a secure box for debugging, it seems that [CrashCatcher](https://github.com/adamgreen/CrashCatcher) is a good choice. By using CrashCather we can capture the register and RAM state at a time of a crash, and through [CrashDebug](https://github.com/adamgreen/CrashDebug) we can do post-mortem debugging.
- Currently vmpu can only load one secure box, and if we want to capture its state when crashed, there is no available box for integrating CrashCather.

```c
void vmpu_load_box(uint8_t box_id)
{
        if(box_id == 0)
             vmpu_switch(0, 0);
        else
             HALT_ERROR(NOT_IMPLEMENTED, "currently only box 0 can be loaded"); 
}
```

THX !

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1887

**Comment by meriac** [comment]
I believe you misread our APIs - vmpu_load_box is an internal API. The way we want to solve this problem in future is the secure debug hook mechanism as described in https://github.com/ARMmbed/uvisor/issues/70 .

I am closing this issue as I regard it as a duplicate to https://github.com/ARMmbed/uvisor/issues/70.
