### ISSUE TITLE
uVisor should not contain its own copy of CMSIS headers

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#132]
Currently, uVisor contains copies of CMSIS headers for each platform it supports. These same headers are available from yotta modules, manufacturer zip files, KEIL packs, and/or other git repos. It'd be nice if uVisor could get the headers from someplace else instead of making yet another unmaintainable copy.

As a positive side effect, this will reduce the cognitive overhead of porting uVisor to a new platform, as one no longer need worry about how to make a maintainable copy of CMSIS definitions that, to quote the porting guide, "keep the header files to a minimum, providing only basic symbols and macros for the platform."

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1907

**Comment by meriac** [comment]
Until uVisor is released (TechCon) i would like to keep compilation self-contained. In future we will still have the requirement to keep our security verification valid by not depending on the underlying CMSIS changes.

A viable solution might be git-sub-repositories for CMSIS which would give us control over upgrading to later versions.
