### ISSUE TITLE
[debug] Allow unprivileged code to provide memory maps and custom fault handlers

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#145]
With the changes introduced in https://github.com/ARMmbed/uvisor/pull/142 uVisor becomes even more hardware-agnostic.

This means that no memory map, IRQ map, LED blinking patterns are available for debugging. We should then provide APIs/mechanisms for unprivileged code to provide such information.

This may fit in the larger picture of a debug box, but for the moment I am creating this issue as an enhancement to keep track of the removed functionality.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2083

**Comment by meriac** [comment]
Closed as a duplicate of https://github.com/ARMmbed/uvisor/issues/70
