### ISSUE TITLE
Not possible to release multiple configurations for a platform

### ISSUE THREAD

**Issue by akselsm** [ARMmbed/uvisor#152]
With the current Makefile.rules, it seems that it isn't possible to release multiple configurations. If I have a Makefile like this for my platform:

```
CONFIGURATIONS:= \
    MY_CONFIG_1 \
    MY_CONFIG_2 \
    MY_CONFIG_3

my_platform_r:
	$(foreach CONFIGURATION, \
	          $(CONFIGURATIONS), \
	          CONFIGURATION=$(CONFIGURATION) make -f ../../core/Makefile.rules clean release && ) true
```

Then only the last configuration will be preserved in `release/source/<platform>/`, since the `release` make target performs `rm -rf $(RELEASE_SRC_HW)`.

If I understand the comments on the refactoring pull request + comments in source code correctly, it should be possible to call `make release` multiple times to output multiple binaries/configurations for the same platform.

**Comment by AlessandroA** [comment]
Thanks a lot for spotting this! It seems pretty simple to fix, I'll issue a PR.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2055
