### ISSUE TITLE
Doc folder missing on master branch

### ISSUE THREAD

**Issue by Darma** [ARMmbed/uvisor#155]
On master branch, in README.md file, section Memory Layout, there is a hyperlink for "**uVisor memory layout**" - https://github.com/ARMmbed/uvisor/blob/master/k64f/docs/memory_layout.png 

But there is no **/k64f** folder. Other branches does have this folder. Please have a look this, thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2089

**Comment by AlessandroA** [comment]
Fixed in https://github.com/ARMmbed/uvisor/pull/162
