### ISSUE TITLE
Allow secure callbacks to box 0

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#185]
Currently secure gateways to box 0 are not allowed.

We should implement a *secure callback* that allows switching context to box 0. This callback would look like any other secure gateway but will allow runtime-determined function pointers to be given as a destination for the callback.

**Comment by AlessandroA** [comment]
@meriac What about the use model? Secure gateways are usually not called explicitly. It's an API that under the hood issues a sgw to itself. In this case,

I guess in this case we want boxes to explicitly ask for a box 0 callback, right? As in "I want to call this function in the context of the main box, not mine." (use case: untrusted functions from other libraries).

**Comment by meriac** [comment]
Will be replaced by remote procedure calls.
