### ISSUE TITLE
Remove UVISOR_DISABLED-specific fallback code

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#196]
We need to generalize the concept of a disabled uVisor, so that `disabled.c` can be removed.

In that scenario, uVisor core would still be used in `UVISOR_DISABLED` mode, with less restrictions and with the MPU/Kinetis peripheral protections disabled.

Currently the file `disabled.c` file implements several fallback implementations of uVisor core, that with time become difficult to maintain. One example is captured by [this commit](https://github.com/ARMmbed/uvisor/pull/195/commits/166cff3fe4f82f7784cd5680712ee6add181c17d).

**Comment by AlessandroA** [comment]
@meriac @patater

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2369

**Comment by meriac** [comment]
already part of uVisor RTOS.
