### ISSUE TITLE
Move unsupported.c into api/unsupported folder

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/uvisor#240]
The `unsupported.c` file contains empty implementations for `uvisor_init` for targets that do not support uVisor natively.

It is not part of uVisor, but compiled by the target build system and should therefore reside in its own folder `api/unsupported`.

**Comment by meriac** [comment]
Fixed in master, see https://github.com/meriac/mbed/tree/0f0b7f55a199220a4ab2aa9c72fe0bebb55786a2/uvisor/targets/TARGET_UVISOR_UNSUPPORTED
