### ISSUE TITLE
No error generated after consuming all mpu regions

### ISSUE THREAD

**Issue by asensaoui** [ARMmbed/uvisor#261]
When uVisor calls the function vmpu_switch(...), during handling mpu regions, if for example we declare more than 8 memory zones in the ACLs it just registers the first one until it consumes all mpu regions and ignores the rest of ACLs without generating any error.

Is there any possibility to use sub-regions in the mpu with uVisor? So we can for example declare a memory zone and then choose which sub-region we want to protect with uVisor.

**Comment by meriac** [comment]
@asensaoui Please keep in mind that vmpu virtualises the MPU regions. This means that you can have an arbitrary amount of MPU regions - and uvisor automatically switches in missing MPU regions whenever needed and accessible to the calling process.
