### ISSUE TITLE
Implement a STATIC_ASSERT macro for uVisor

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#288]
We currently need a STATIC_ASSERT macro to catch errors at compile time. The macro should produce very user friendly output; implementations that have cryptic error messages are unacceptable. The macro implementation must also work from both inside and outside of function scope.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2804

**Comment by thomasfangyi** [comment]
http://en.cppreference.com/w/c/language/_Static_assert

**Comment by Patater** [comment]
Fixed via https://github.com/ARMmbed/uvisor/pull/478
