### ISSUE TITLE
v7M MPU does not implement ACL round-up

### ISSUE THREAD

**Issue by nchong** [ARMmbed/uvisor#299]
The procedure `vmpu_acl_update_box_region` in `core/system/src/mpu/vmpu_armv7m.c` currently handles round-down but not round-up. This means non-power of two sizes that request round-up will fail at the alignment check.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2836

**Comment by nchong** [comment]
This issue can be closed. Rounding is occurring within `vmpu_acl_update_box_region` due to the call to `vmpu_region_bits` which gives ceil(log2(size)):

```
bits = vmpu_region_bits(size);
size_rounded = 1UL << bits;
```
