### ISSUE TITLE
On kinetis platform, we have too many debug strings

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#337]
Our kinetis debug build is bumping up against the limits of flash due to all the nice debug strings we've added. We should come up with a way to reduce the flash pressure without sacrificing the suitability of the debug build for debugging.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2932

**Comment by AlessandroA** [comment]
Fixed by https://github.com/ARMmbed/uvisor/pull/368
