### ISSUE TITLE
Method to detect whether current code is being executed as a result of an IRQ

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/uvisor#34]
For some library functions, it is important, for fault detection, to know whether the API has been called as part of the call tree of an IRQ.

Examples:
* Memory allocators
* Some scheduler functions, e.g. ```postCallbackAgain()```

It may be adequate to document that these should not be done, but runtime checks are more direct.

**Comment by AlessandroA** [comment]
Implemented in https://github.com/ARMmbed/uvisor/issues/57
