### ISSUE TITLE
Rethink UVISOR_STACK_BAND_SIZE intention and implementation

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/uvisor#340]
[Current implementation](https://github.com/ARMmbed/uvisor/search?utf8=✓&q=UVISOR_STACK_BAND_SIZE).

On the K64F port, we use two regions for the box bss and the box stack, with a 128B (=`UVISOR_STACK_BAND_SIZE`) memory band in between, protected by the background region.

On the v7-M MPU, we only have one MPU region for both bss and stack, so we use a disabled subregion to have a stack band. However, this is done using a 8/6 multiplication [in this box macro](https://github.com/ARMmbed/uvisor/blob/master/api/inc/box_config.h#L77-L89), which is no compatible with the define.

We should rethink how we approach this, since this is confusing and the 8/6 multiplication is wasteful on K64F.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2933

**Comment by AlessandroA** [comment]
Will be fixed when fixing: https://github.com/ARMmbed/uvisor/issues/206
