### ISSUE TITLE
Create a page eviction API

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#361]
For testing that uVisor behaves correctly when certain pages are active or inactive, it is necessary to have a page eviction API that can mark a page as inactive. All tests written so far attempt to verify the correct behavior of page handling by allocating many small pages and relying on unspecified behavior of which pages are evicted when all MPU regions become full. These tests are brittle, breaking even for small changes in the page caching algorithm employed.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-162

**Comment by AlessandroA** [comment]
Fixed in https://github.com/ARMmbed/uvisor/pull/356.
