### ISSUE TITLE
Make the debug build less space constrained

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#363]
Remove m451 from the list of debug targets, so that we can increase the flash available to uVisor in debug builds beyond what that target can support. This will give uVisor debug builds some more headroom to avoid failing due to lack of flash space.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-160

**Comment by AlessandroA** [comment]
Fixed in https://github.com/ARMmbed/uvisor/pull/368
