### ISSUE TITLE
Add register level security for RCC/EXTI/SYSCFG

### ISSUE THREAD

**Issue by meriac** [ARMmbed/uvisor#38]
Currently access is granted to RCC, EXTI and SYSCFG - for all of these registers access can't be directly granted, but filtered per register / bit. Especially SYSCFG is security critical as it allows re-mapping of the RAM/FLASH memory.

As a result we added the new concept called "Register Level Access Security" as seen in https://github.com/ARMmbed/uvisor-lib/blob/master/uvisor-lib/register_gateway.h#L90 .

Our solution creates a similar  mechanism as the call gateway, but for registers - the register level gateway can grant access to a set of bits of a single register - avoiding the creation of large ACLs covering the whole region.
As the access is specified in flash an attacker can't get access to other bits or using a different box context - as long as write access is blocked to flash.

The implementation is currently undergoing and needs to be released to fix this problem.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-909

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1042

**Comment by meriac** [comment]
See https://github.com/mbedmicro/mbed/blob/master/hal/targets/cmsis/core_cmSecureAccess.h and https://github.com/ARMmbed/uvisor/blob/master/api/inc/register_gateway.h
