### ISSUE TITLE
Nested interrupts are currently not supported

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/uvisor#384]
Since the switch to CMSIS RTOS, we have disabled support for nested interrupts.

Nested interrupts require a special state keeping procedure to make sure that the correct context is switched back on interrupt return. The port to CMSIS RTOS broke the original implementation, which needs to be re-adapted.

For the moment nested IRQs will not be allowed.

This only applies when uVisor is enabled on a target platform.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-235

**Comment by Patater** [comment]
Duplicate of #345
