### ISSUE TITLE
Async serial doesn't work with uVisor enabled

### ISSUE THREAD

**Issue by Patater** [ARMmbed/uvisor#397]
All serial async won't work when uVisor is enabled until NVIC_EnableIRQ can claim ownership of IRQs for a box. (Currently, only NVIC_SetVector can claim ownership of an IRQ for a box.)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-252

**Comment by Patater** [comment]
Fixed in uVisor v0.28.1 with mbed OS 5.5. IRQs are now claimed with ACLs.
