### ISSUE TITLE
Pages no in the YAML

### ISSUE THREAD

**Issue by iriark01** [ARMmbed/uvisor#410]
Some of your docs pages aren't in the YAML (for example api\API.md). This means they don't get built on the docs site.

Please can you update the YAML (https://github.com/ARMmbed/uvisor/blob/master/mkdocs.yml) with the pages you want exposed? 

Thank you,

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-293

**Comment by iriark01** [comment]
https://github.com/ARMmbed/uvisor/pull/419

**Comment by AlessandroA** [comment]
Fixed in #419.
