### ISSUE TITLE
Docs: Dead links in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by rjpdasilva** [ARMmbed/uvisor#415]
Following excerpts have dead links:

> * If you want to submit a bug report please make sure to follow our
  [reporting guidelines](https://github.com/ARMmbed/mbed-os/blob/master/Reporting%20Bugs.md).

> * If you want to submit a patch, please read the
  [contribution guide](https://github.com/ARMmbed/mbed-os/blob/master/Contributing%20to%20mbed.md).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-306

**Comment by AlessandroA** [comment]
Fixed in #425
