### ISSUE TITLE
QUICKSTART: do it in DISCO_F429ZI cause RTX error code: 0x00000001

### ISSUE THREAD

**Issue by BaikalHu** [ARMmbed/uvisor#426]
Porting the code to DISCO_F429 board, when press the button 8 times, printing:
Thread count between button presses: 7 2 3 2 3 2 2 3 
RTX error code: 0x00000001, task ID: 0x00000000

The error code meams OS_ERR_STK_OVF, and the stack size is 1024. I didn't find which cause the error.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-335

**Comment by Patater** [comment]
Hi @BaikalHu

We believe we've fixed this issue in the mbed OS 5.5 release of uVisor. Please try reproducing with the mbed OS 5.5 release.

Thanks
