### ISSUE TITLE
Shall armv8m scheduler update thread information in RTX5 ? (ARMv8M)

### ISSUE THREAD

**Issue by p03189** [ARMmbed/uvisor#433]
In uVisor for armv8m, the scheduler is responsible for switching boxes. I can't figure when thread information of RTX5 (osRtxInfo.thread.run) is updated by the scheduler. Is it a TODO item as your comment in uvisor/core/system/src/core_armv8m/scheduler.c ?
"// TODO copy state with memcpy by sharing the struct type in both places"

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-378

**Comment by Patater** [comment]
In uVisor for armv8m, the scheduler does not and will not update osRtxInfo.thread.run. The uVisor scheduler switches boxes with SysTick_S. RTX5 uses SysTick_NS to schedule threads.
