### ISSUE TITLE
Inconsistent coding style

### ISSUE THREAD

**Issue by jserv** [ARMmbed/uvisor#46]
Comparing to other ARM mbed projects such as [mbed-drivers](https://github.com/ARMmbed/mbed-drivers) and [mbed-client](https://github.com/ARMmbed/mbed-client), I found that the existing coding style in `uvisor` is a bit inconsistent. For example, the keyword `if` in C program statement usually lacks of corresponding space in `uvisor`, but both `mbed-drivers` and `mbed-client` have the explicit space: `if (...)`.

I just wonder if there is the documentation about coding style globally applied to all mbed projects.

**Comment by hugovincent** [comment]
Hi @jserv -- good spot, you're right. We have some inconsistencies across mbed OS wrt code style, including here. We have [this document](https://developer.mbed.org/teams/SDK-Development/wiki/mbed-sdk-coding-style) about the coding style in mbed classic, but it needs some updates for mbed OS.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-908

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1041

**Comment by meriac** [comment]
(closed, all new code has been added with new convention, pre-existing code changed as we proceed)
