### ISSUE TITLE
Support ARMv8M M23?

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/uvisor#514]
I find there has been code for ARMv8M M33 by checking this commit (cb31268 Merge pull request #489 from orenc17A/master). Do you have any plan to support M23?
@Patater

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-454

**Comment by Patater** [comment]
I can't comment, sorry.

**Comment by ccli8** [comment]
We Nuvoton have co-operation with you on our first Cortex-M23 chip (**M2351**, mbed target name would be **NUMAKER_PFM_M2351**). It would be much appreciated if you could give some information regarding mbed/uVisor support for M23 chips, and then we can follow. That would help for our promotion.
