### ISSUE TITLE
time（）function error

### ISSUE THREAD

**Issue by gylalahuo** [ARMmbed/uvisor#522]
Board:K64F
Program:
#include "uvisor-lib/uvisor-lib.h"
#include "mbed.h"
#define MAIN_ACL(acl_list_name) \
    static const UvisorBoxAclItem acl_list_name[] = {     \
        {MCG,    sizeof(*MCG),    UVISOR_TACLDEF_PERIPH}, \
        {SIM,    sizeof(*SIM),    UVISOR_TACLDEF_PERIPH}, \
        {OSC,    sizeof(*OSC),    UVISOR_TACLDEF_PERIPH}, \
        {PORTB,  sizeof(*PORTB),  UVISOR_TACLDEF_PERIPH}, \
        {PORTC,  sizeof(*PORTC),  UVISOR_TACLDEF_PERIPH}, \
        {PORTA,  sizeof(*PORTA),  UVISOR_TACLDEF_PERIPH}, \
        {PORTD,  sizeof(*PORTD),  UVISOR_TACLDEF_PERIPH}, \   
        {PORTE,  sizeof(*PORTE),  UVISOR_TACLDEF_PERIPH}, \
        {RTC,    sizeof(*RTC),    UVISOR_TACLDEF_PERIPH}, \
        {LPTMR0, sizeof(*LPTMR0), UVISOR_TACLDEF_PERIPH}, \
        {PIT,    sizeof(*PIT),    UVISOR_TACLDEF_PERIPH}, \
        {SMC,    sizeof(*SMC),    UVISOR_TACLDEF_PERIPH}, \
        {UART0,  sizeof(*UART0),  UVISOR_TACLDEF_PERIPH}, \     
        {SPI0,  sizeof(*SPI0),  UVISOR_TACLDEF_PERIPH}, \
        {RNG,  sizeof(*RNG),  UVISOR_TACLDEF_PERIPH}, \	
    }

MAIN_ACL(g_main_acl);
UVISOR_SET_MODE_ACL(UVISOR_ENABLED,g_main_acl);
UVISOR_SET_PAGE_HEAP(8*1024,5);
Serial pc(PTA2, PTA1, 115200);

uint8_t __attribute__((section(".keep.uvisor.bss.boxes"),aligned(32))) __box_overhead(8096);

int main()
{
	pc.printf("start");
	int c_time=time(NULL);
	pc.printf("%d\r\n",c_time);
	
}

step1 :
compile command mbed compile -m K64F -t GCC_ARM -c --profile mbed-os/tools/profiles/debug.json
step2: debug
           when i use "c" command in gdb windows,only printf  "start" ,and  it hang in time() function .
          
recently i learn how to use uvisor to secure https communication ,it"s the problem i met. and by the way,
i successed run this demo once,it printfed the time ,but when i try again ,it never successful.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-483

**Comment by alzix** [comment]
duplicates #453
