### ISSUE TITLE
malloc doesn't call secure_malloc() function

### ISSUE THREAD

**Issue by gylalahuo** [ARMmbed/uvisor#528]
From the uvisor-rtos-docs. there is a mesaage that .
The current allocator is transparently swapped out by the scheduler to provide the canonical memory management functions malloc, realloc and free to processes and threads. This means that calling any of these three standard memory functions, automatically uses the provided allocator.
Does this mean that use malloc whill call secure_malloc()?
i debug the program ,step into malloc(), it seems doesn't call secure_malloc(). Using secure_malloc can succeed get 16K memory .Using  malloc() can't get the memory.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-502
