### ISSUE TITLE
m_data_2 overflowed

### ISSUE THREAD

**Issue by gylalahuo** [ARMmbed/uvisor#530]
In my program there are many malloc() call.If i don't enable uvisor. No problem. when I enable uvsior , malloc() call usually go to fail. then i replace malloc() by secure_malloc() ,but there still have this problem .
so i revise MK64FN1M0XXX12.ld file ,set  _heap_size__=0x20000. compile the program, the error log  is "region m_data_2 overflow by 46040". In .ld file the m_data_2 origin=0x20000000, LENGTH=0X30000>0X20000?
so why  have this problem when i revise __heap_size=0x20000.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-504
