### ISSUE TITLE
new a private box ,there is an error”  .uvisor.bss is not within region m_data，”

### ISSUE THREAD

**Issue by gylalahuo** [ARMmbed/uvisor#532]
Board:K64F

the .uvisor.bss region and private box  heap  region which is allocated by UVISOR_BOX_HEAPSIZE() both in m_data  region , is it rigth?

In my program ,there are two private BOX ,a,b. and I want to new a  another private BOX c,when i do it,an error occured.
here is my box configuration:
BOX A configuration:
UVSIOR_BOX_HEAPSIZE(20*1024);
UVISOR_BOX_MAIN(my_box_main,osPriorityNormal,4*1024);
UVISOR_BOX_CONFIG(my_box_main,acl,128,my_box_context);

BOX B configuration:
UVSIOR_BOX_HEAPSIZE(3*1024);
UVISOR_BOX_MAIN(number_store_main.osPriorityNormal,1*1024);
UVISOR_BOX_CONFIG(box_number_store,acl,128,box_context);

BOX C configuration:
UVSIOR_BOX_HEAPSIZE(1*1024);
UVISOR_BOX_MAIN(number_store_main.osPriorityNormal,1*1024);
UVISOR_BOX_CONFIG(aes,acl,256,context);

 I dont want revise BOX A and BOX B configuration，because it will raise another problem. so  there is a way to solve this problem.? If can't, please tell me, and i will show it to my teacher that it's wrong to realise this function. 
Thanks!
the error log ：
![a](https://user-images.githubusercontent.com/14195920/33542965-213e703a-d910-11e7-811b-b9d18e087f7a.PNG)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-517
