### ISSUE TITLE
where can i find the so called "ARM Internal Ref: IOTSEC-XXX "

### ISSUE THREAD

**Issue by shiningfrog** [ARMmbed/uvisor#535]
hello , as the issue ,could anyone tell me where to access it ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-533

**Comment by alzix** [comment]
We are duplicating every GitHub issue to our **Internal** bug tracking system.
To access it you must be formal ARM employee.
You can do that by submitting your CV to https://www.arm.com/careers/index.html 😄
