### ISSUE TITLE
if I define a function in a BOX，is it belong to this BOX?

### ISSUE THREAD

**Issue by gylalahuo** [ARMmbed/uvisor#537]
For example: 
in public BOX 
there are a functions ,
int recv()
in private BOX1
there a function 
int aes_test()

whether the aes_test() belongs to BOX1, recv() belongs to public BOX?and if i define  aes_test() in BOX1, is it secure?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-559

**Comment by alzix** [comment]
uVisor only protecta an execution context. 
The function itself can be implemented as a part of any box. In addition the very same functions can be reused in different boxes, this allows reducing code size
