### ISSUE TITLE
Add symbol support to uvisor_read & uvisor_write APIs

### ISSUE THREAD

**Issue by meriac** [ARMmbed/uvisor#90]
- currently uvisor_read & *_write do not accept structures member addresses
- affects user experience as addresses need to be calculated on the fly

Example:
```C
uvisor_read(&UART0->BAUD_RATE)
```
needs currently to be written as:
```C
uvisor_read(UART0_ADDRESS + UART_BAUD_RATE_OFFSET)
```

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1121

**Comment by meriac** [comment]
Resolved by the new Register Level Access API: https://github.com/mbedmicro/mbed/blob/master/hal/targets/cmsis/core_cmSecureAccess.h
